#指定Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

#指定应用名
#spring:
#  application:
#    name: Customer

spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: Customer-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: Customer-test
#  请保存为UTF-8格式