spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: Customer-dev
version: v-de

---
spring:
  profiles: test   #测试环境
  application: 
    name: Customer-test
version: v-test
#  请保存为UTF-8格式
